name: ci

on:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [ 22.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        # npx force-resolutions : in case of Permission denied: run it locally to fix package-lock.json
        run: |
          echo "install"
          npm install
          echo "show outdated (if any)"
          npm outdated --depth=3 || echo "you must think about update your dependencies :)"

      - name: Run tests
        run: npm run test
